name: ORT Analyzer and Scanner with EPSS Extraction

on:
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache ORT results
        uses: actions/cache@v4
        with:
          path: |
            ~/.ort/cache
          key: ort-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ort-cache-${{ runner.os }}-

      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          vcs-url: 'https://github.com/WebGoat/WebGoat.git'
          run: >
            cache-dependencies,
            labels,
            analyzer,
            evaluator,
            advisor,
            scanner,
            reporter,
            upload-results
          scanner: 'ScanCode'
          ort-version: '53.0.0'
          ort-cli-args: '-P ort.scanner.skipExcluded=true '
          reporter-cli-args: '--reporter.output-dir=tools/ort-results'
          evaluator-cli-args: '--rules-file=.ort/rules/custom-rules.kts'
          ort-cli-scan-args: '--package-types=PROJECT'
          report-formats: 'WebApp,CycloneDx,SpdxDocument,PdfTemplate,EvaluatedModel'

      - name: Ensure tools/ort-results exists and list contents
        run: |
          echo "Checking tools/ort-results..."
          if [ -d "tools/ort-results" ]; then
            echo "ORT reports generated:" && ls -R tools/ort-results
          else
            echo "tools/ort-results directory does NOT exist." && exit 1

      - name: Upload ORT reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ort-results
          path: tools/ort-results

      - name: Install Python and dependencies for EPSS
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install requests

      - name: Run EPSS extraction script
        run: |
          python3 scripts/extract_epss.py tools/ort-results/advisor-results.json

      - name: Upload EPSS report
        uses: actions/upload-artifact@v4
        with:
          name: epss-results
          path: tools/epss/epss-results.json
          

