name: ORT Analyzer
on:
  workflow_dispatch:
 
jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
 
      - name: Set up ORT config directory and file
        run: |
          mkdir -p ~/.ort/config
          cat <<EOF > ~/.ort/config/config.yml
          scanner:
            options:
              ScanCode:
                processes: 1
          EOF
 
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          vcs-url: 'https://github.com/rsuite/rsuite'
          allow-dynamic-versions: 'true'
          run: >
              cache-dependencies,
              labels,
              analyzer,
              scanner,
              advisor,
              evaluator,
              reporter,
              upload-results
          ort-cli-args : '-P ort.scanner.skipExcluded=true ort.analyzer.enabledPackageManagers=NPM'
          ort-cli-scan-args: '--package-types=PROJECT'
